name: release

on:
  release:
    types: [published]

jobs:
  publish-mod:
    environment: Mod Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set output variables
        id: vars
        run: |
          filename="${{ vars.FACTORIO_MOD_NAME }}_${{ github.event.release.tag_name }}"
          echo "filename=$filename" >> $GITHUB_OUTPUT
      - name: Compress/Decompress
        uses: somaz94/compress-decompress@v1.0.3
        with:
          command: compress
          source: .
          format: zip
          dest: "./${{ steps.vars.outputs.filename }}.zip"
      - name: Upload to Factorio 
        uses: mchangrh/factorio-mod-upload@v1
        with:
          mod-name: ${{ vars.MOD_NAME }}
        env:
          FACTORIO_MODS_TOKEN: ${{ secrets.FACTORIO_TOKEN}}
          FILENAME: ${{ steps.vars.outputs.filename }}.zip
